#!/bin/bash

# Git
sudo apt-get update -y
sudo apt-get install -y build-essential git
echo "alias g='git'" >> ~/.bashrc
git config --global color.ui auto
git config --global core.editor vim
git config --global alias.st status
git config --global alias.br branch
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.l 'log --color --graph --pretty=oneline --decorate --date=short --abbrev-commit --branches'
git config --global alias.ds 'diff --stat'
git config --global diff.tool vimdiff
git config --global merge.tool vimdiff
git config --global difftool.prompt false
git config --global alias.dt difftool
git config --global alias.mt mergetool

git clone https://github.com/usutani/dotfiles.git ~/dotfiles
ln -s ~/dotfiles/_bash_profile ~/.bash_profile
ln -s ~/dotfiles/_vimrc ~/.vimrc
ln -s ~/dotfiles/_tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/_oracle_client ~/.oracle_client

# Vim: Replace vim-tiny
sudo apt-get install -y vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# tmux
sudo apt-get install -y tmux
